{
        'content_type': 'text', 
        'message_id': ****, 
        'from_user': {'id': **********, 'is_bot': False, 'first_name': '****', 'username': None, 'last_name': None, 'language_code': 'ru', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None}, 
        'date': 1605470782, 
        'chat': {'id': (********, 'type': 'private', 'title': None, 'username': None, 'first_name': '****', 'last_name': None, 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'sticker_set_name': None, 'can_set_sticker_set': None}, 
        'forward_from': None, 
        'forward_from_chat': None, 
        'forward_from_message_id': None, 
        'forward_signature': None, 
        'forward_date': None, 
        'reply_to_message': None, 
        'edit_date': None, 
        'media_group_id': None, 
        'author_signature': None, 
        'text': '030', 
        'entities': None, 
        'caption_entities': None, 
        'audio': None, 
        'document': None, 
        'photo': None, 
        'sticker': None, 
        'video': None, 
        'video_note': None, 
        'voice': None, 
        'caption': None, 
        'contact': None, 
        'location': None, 
        'venue': None, 
        'animation': None, 
        'dice': None, 
        'new_chat_member': None, 
        'new_chat_members': None, 
        'left_chat_member': None, 
        'new_chat_title': None, 
        'new_chat_photo': None, 
        'delete_chat_photo': None, 
        'group_chat_created': None, 
        'supergroup_chat_created': None, 
        'channel_chat_created': None, 
        'migrate_to_chat_id': None, 
        'migrate_from_chat_id': None, 
        'pinned_message': None, 
        'invoice': None, 
        'successful_payment': None, 
        'connected_website': None, 
        'json': 
            {'message_id': *******, 
             'from': 
                {'id': *********, 
                 'is_bot': False, 
                 'first_name': 'Egor', 
                 'language_code': 'ru'}, 
             'chat': 
                {'id': **********, 
                 'first_name': 'Egor', 
                 'type': 'private'}, 
             'date': 1605470782, 
             'text': '030'}
}
